site:
  url: https://openapi.tools
description: A site to find the right tools for developers to build with the OpenAPI  
collections_dir: /reviews
collections:
  reviews:
    name: OAI Tools
    output: true
    permalink: /reviews/:tool
    relative_directory: /reviews