site:
  url: https://openapi.tools
description: A site to find the right tools for developers to build with the OpenAPI  
collections_dir: /tools
collections:
  tools:
    slug: format
    name: OAT Tools
    output: true
    permalink: /tools/:title