site:
  url: https://openapi.tools
description: A site to find the right tools for developers to build with the OpenAPI  
collections_dir: /reviews
collections:
  reviews:
    slug: format
    name: OAT Tools
    output: true
    permalink: /reviews/:slug